# Generated by Django 2.1 on 2018-08-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('complexity', models.IntegerField()),
            ],
        ),
    ]
